#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'countingValleys' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER steps
#  2. STRING path
#

def countingValleys(steps, path):
    # Write your code here
    steps_len = len(path)
    counter = 0 
    valleys = 0 
    
    for i in range (0,steps_len):
        if (path[i] == 'U'):
            counter = counter + 1
        else:
            counter = counter - 1  
        if (counter == 0 and path[i] == 'U'):
            valleys = valleys+1
            print ("# of valleys = ", valleys)
    
    return valleys
    

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    steps = int(input().strip())

    path = input()

    result = countingValleys(steps, path)

    fptr.write(str(result) + '\n')

    fptr.close()
